### ISSUE TITLE
Can't catch little bit complex any type

### ISSUE THREAD

**Issue by darky** [plantain-00/type-coverage#11]
For example `any[]` or maybe `Promise<any>`
Desire to catch like this too.

**Comment by darky** [comment]
Maybe need to add some `blacklist` option, which contains array of uncovered types...

**Comment by plantain-00** [comment]
After some investigations, I can check `any` in type arguments(like `any[]` and `Promise<any>`) , enabled by a flag like `--complex`
Is there any other cases that you want it gets checked?
What do you mean about `uncovered types`?

**Comment by darky** [comment]
I mean on uncovered type some container like: `Array<any>`, `Promise<any>`, `PromiseLike<any>`, `Something<any>`, ... e.t.c
Need to have universal way for find any type in container.
Not hardcode.
If it so hard, suggest `blacklist` option and user can consider own uncovered types :)

**Comment by plantain-00** [comment]
v1.7.0 released now
