### ISSUE TITLE
Check coverage of staged/added files

### ISSUE THREAD

**Issue by StaRenn** [plantain-00/type-coverage#115]
It would be awesome if you could check coverage of added/staged files for precommit hook. Coverage of added file less than 95%? No commit for you

I think it needs feature that will allow you to pass paths in cli like eslint or prettier "eslint **/*.(ts|tsx)" so you can run it in lint-staged

**Comment by plantain-00** [comment]
`2.23.0` supports checking specific files by adding `-- file1.ts file2.ts` now

**Comment by StaRenn** [comment]
Works fine, thank you!
