### ISSUE TITLE
type-coverage -p command yielding different results from different root directories

### ISSUE THREAD

**Issue by spaul1042** [plantain-00/type-coverage#123]
#### Environment(if relevant):
Vs code , React Typescript based project

#### Code(if relevant):

```
// code here
```

#### Expected:
I have a packages folder where there are different packages whose type-coverage rate I want to calculate. There is a package named "board" and another package named "proto". 

I am testing the type-coverage commands on these two terminals.
In Terminal 1 , I am in   >> src/packages/
In Terminal 2 , I am in   >> src/packages/proto

Command I run on Terminal 1 :  type-coverage -p  board
Command I run on Terminal 2 :  type-coverage -p ../board

I must get the same type coverage rate in bot the terminals.

#### Actual:
On Terminal 1 I get  >> 396027/40714,  97.27 %
On Terminal 2 I get  >> 608/662.  91.84 %

Am I missing something here as the type-coverage command is installed globally.

**Comment by plantain-00** [comment]
The result in files start with `..` will be ignored, to fix #42 : https://github.com/plantain-00/type-coverage/blob/7aa9475f7ef8c3b15f994a7b4bd88496f919ceed/packages/core/src/core.ts#L43-L45

**Comment by spaul1042** [comment]
I want to run type-coverage commands from a directory named `type-coverage` present in the script directory. and script folder is there in the root of the project. do you suggest something that I can do?

**Comment by spaul1042** [comment]
> The result in files start with `..` will be ignored, to fix #42 :
> 
> https://github.com/plantain-00/type-coverage/blob/7aa9475f7ef8c3b15f994a7b4bd88496f919ceed/packages/core/src/core.ts#L43-L45

**Comment by plantain-00** [comment]
Maybe your script can be like something `cd .. && type-coverage -p ./src`

**Comment by spaul1042** [comment]
Even When I cd into the a package  of the packages directory , and then run `type-coverage -p . ` Even this yielding a different answer.

**Comment by plantain-00** [comment]
`v2.26.0` add `--not-only-in-cwd` to disable this behavior.

**Comment by spaul1042** [comment]
Okay thanks!
