### ISSUE TITLE
The '--no-detail-when-failed' option does not work

### ISSUE THREAD

**Issue by deongroenewald** [plantain-00/type-coverage#126]
#### Environment(if relevant):
Node v18.14.1
#### Expected:
- Passing the '--no-detail-when-failed' option **should not** show detail message when the CLI failed.
- Passing the '--noDetailWhenFailed' option **should not** show detail message when the CLI failed.

#### Actual:
- Passing the '--no-detail-when-failed' option **does** show detail message when the CLI fails.
- Passing the '--noDetailWhenFailed' option **does not** show detail message when the CLI fails.

**Comment by plantain-00** [comment]
#113
