### ISSUE TITLE
@type-coverage-ignore

### ISSUE THREAD

**Issue by darky** [plantain-00/type-coverage#13]
For example:

```typescript
try {
  // some code...

// @type-coverage-ignore
} catch (e) {}
```

And type-coverage not scan this line of code.
Otherwise, I can't hide it from from type-coverage. For example:

```typescript
try {
  // some code...
} catch (e: Error) {}
```
Get error: `[ts] Catch clause variable cannot have a type annotation. [1196]`

**Comment by plantain-00** [comment]
v1.9.0 support this now: https://github.com/plantain-00/type-coverage#ingore-line

**Comment by darky** [comment]
Cool! Thanks! But unfortunately this regression appeared in 1.9.0
https://github.com/plantain-00/type-coverage/issues/14
