### ISSUE TITLE
Incompatibility with zod schemas

### ISSUE THREAD

**Issue by molinch** [plantain-00/type-coverage#134]
First of all thanks for the awesome library, this truly helps us to achieve high quality in our TS projects.

#### Code:

```ts
const someSchema = z.object({
  someArray: z.array(
    z.object({
      value: z.boolean(),
    }),
  ),
})
```
This simple zod schema will report 2 errors that the type contains any. See:
![image](https://github.com/plantain-00/type-coverage/assets/5130190/2f863d0f-b1ae-4443-a2f9-26b6831c3782)
Indeed the type definition from zod has "strip ZodTypeAny", but that means exactly that any isn't allowed.

#### Expected:
No error due to the zod schema being defined

#### Actual:
Errors whenever using zod, thus we resort to the annoying:
![image](https://github.com/plantain-00/type-coverage/assets/5130190/d1abd0ac-2c28-4f3e-881f-d6fa38002476)

If there would be a workaround it would be super cool

**Comment by plantain-00** [comment]
it's `any` is in type arguments, you.can ignore them by `--ignore-nested`

**Comment by molinch** [comment]
Thanks so much for the prompt feedback @plantain-00 :)
