### ISSUE TITLE
Feature request: ignore certain files

### ISSUE THREAD

**Issue by danvk** [plantain-00/type-coverage#23]
I have some files in my project which are just demos / development aids and I'm less worried about `any` types in them. I can add them to the `exclude` section of my `tsconfig.json` to exclude them from type-coverage, but this will also disable type checking in them.

What would you think of an `--ignore-files` option, or a `@type-coverage-ignore-file` directive?

Great tool, btw!

**Comment by plantain-00** [comment]
v1.14.0 support `--ignore-files` now

**Comment by danvk** [comment]
Beautiful! Thanks for the speedy turnaround.
