### ISSUE TITLE
Does not understand "evolving any"

### ISSUE THREAD

**Issue by danvk** [plantain-00/type-coverage#28]
#### Code(if relevant):

TypeScript has a notion of an "evolving `any`" type. If `noImplicitAny` is set and a type is left uninitialized, its type will get set based on whatever you assign to it. The comments in this snippet show the type of `val` if you hover over it on each line:

```ts
let val;  // any
if (Math.random() < 0.5) {
  val = /hello/;  // any
  val  // RegExp
} else {
  val = 12;  // any
  val  // number
}
val  // number | RegExp
```

While several of these `val`s do have `any` types, they are not harmful and probably shouldn't be counted against you for type coverage. This feature was added back in TypeScript 2.1. You can read more about it in the [release notes][1].

#### Expected:

100% type coverage

#### Actual:

The three lines on which `val` has an `any` type are marked as misses for type-coverage.

[1]: https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#improved-any-inference

**Comment by plantain-00** [comment]
This tool just counts identifiers whose type is not any, so seems right here.
And it's not reasonable if `val` used at line 2 but this tool says 100% type coverage.
You can fix this by `let val: number | RegExp;`

**Comment by danvk** [comment]
That annotation would not improve the type safety of this code. While `val`'s type is shown as `any` if you inspect it, you cannot "observe" that type in code without triggering an error:

```ts
function range(start: number, limit: number) {
  const out = [];  // any[]
  //    ~~~ Variable 'out' implicitly has type 'any[]' in some
  //        locations where its type cannot be determined.
  if (start === limit) {
    return out;  // any[]
    //     ~~~ Variable 'out' implicitly has an 'any[]' type.
  }
  for (let i = start; i < limit; i++) {
    out.push(i);  // any[]
  }
  return out;  // number[]
}
```

I'd say the correct behavior is to ignore `any` types that are assigned to while they are evolving, i.e. don't include them in either the numerator or the denominator. I'm not sure if TypeScript's API exposes whether an `any` type is "evolving" at any particular point, so this might be difficult.

**Comment by plantain-00** [comment]
It still seems unreasonable to me, it should be annotated as union type (like `number | string | ...`) or `unknown`(if it is really undetermined when declared)

**Comment by danvk** [comment]
Why? This is just a form of type inference. Not every type needs to be explicit.
