### ISSUE TITLE
Doesn't work with TypeScript 2.9 (Unknown compiler option 'keyofStringsOnly')

### ISSUE THREAD

**Issue by karol-majewski** [plantain-00/type-coverage#3]
#### Environment(if relevant):

TypeScript 2.9.1 with `"keyofStringsOnly": true` in `tsconfig.json`.

#### Expected:

Runs without error.

#### Actual:

Throws with following error:

```js
[
  {
    file: undefined,
    start: undefined,
    length: undefined,
    messageText: "Unknown compiler option \'keyofStringsOnly\'.",
    category: 1,
    code: 5023
  }
]
```

Shouldn't TypeScript be listed as a peer dependency?

**Comment by plantain-00** [comment]
v1.1.0 add support for typescript 2.9.1, it should fix this issue

**Comment by karol-majewski** [comment]
Works fine now, thank you.
