### ISSUE TITLE
Integrating with PRs and GitHub

### ISSUE THREAD

**Issue by krzkaczor** [plantain-00/type-coverage#30]
First of all, I love this package 👍 I think type coverage can be a really useful metric for many TypeScript projects.

I am the creator of an open-source platform — [codechecks.io](https://codechecks.io) that allows for creating plugins (codechecks) that can plug directly into GitHub PR interface. With this library, I created a prototype of a codecheck that continuously tracks type coverage between PRs https://github.com/codechecks/type-coverage-watcher in TypeScript projects.

I am curious if you're interested in merging or cross-promoting these projects together. `type-coverage-watcher` uses your package under the hood. Currently, `type-coverage-watcher` is pretty basic but it can calculate how type coverage changes across the PRs and show new untyped variables.

Let me know what do you think 🙏

**Comment by plantain-00** [comment]
OK

**Comment by krzkaczor** [comment]
@plantain-00 so, is it fine for you if I would make a PR with information about how to plug this package into a PR flow and a link to https://github.com/codechecks/type-coverage-watcher ?

I imagine that it would look similar to https://github.com/cgewecke/eth-gas-reporter#continuous-integration-in-circleci readme

**Comment by plantain-00** [comment]
Yes, it's fine

**Comment by krzkaczor** [comment]
Thanks! I will prepare something later today.
