### ISSUE TITLE
[ts-lib-utils] `extends` of tsconfig is not resolved correctly

### ISSUE THREAD

**Issue by whatasoda** [plantain-00/type-coverage#33]
#### Environment(if relevant):
This is dummy `tsconfig.json`, I have another `tsconfig` in my `node_modules` directory
```
{
  "extends": "my-tsconfig/react",
  "compilerOptions": {
    ...
  },
  "include": [...],
  "exclude": ["node_modules"]
}
```

#### Expected:
Works without error

#### Actual:
CLI threw error:
```
ENOENT: no such file or directory, stat '/Users/whatasoda/my-project/my-tsconfig/react'
```

**Comment by whatasoda** [comment]
The cause may be from here:
https://github.com/plantain-00/type-coverage/blob/06b1c41f8fc1c604710205254e68d9c2c0e02df6/packages/utils/src/tsconfig.ts#L61-L66

I'll make a PR

**Comment by plantain-00** [comment]
What's the path of `tsconfig.json`(your `"extends": "my-tsconfig/react"`)?
I don't know how to reproduce it.

**Comment by whatasoda** [comment]
Sorry, my example was a little confusing.
Here is new example, I want to extend tsconfig with my private package.

```
.
|-- node_modules
|   `-- @whatasoda
|       `-- tsconfig
|           `-- tsconfig.react.json
|-- package.json
`-- tsconfig.json
```

`tsconfig.json`
```
{
  "extends": "@whatasoda/tsconfig/tsconfig.react",
  "compilerOptions": {
    "target": "es3"
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules"]
}

```

`node_modules/@whatasoda/tsconfig/tsconfig.react.json`
```
{
  "compilerOptions": {
    "jsx": "react",
    ...
  }
}
```

**Comment by whatasoda** [comment]
I think you should tweak behavior of `tsc` about resolving config file.

How `tsc` resolve config file path is:
https://github.com/microsoft/TypeScript/blob/dbe9e3d237ee82435ef3948b3c479d548ab66b3d/src/tsc/tsc.ts#L99-L124

Then `tsc` do:
https://github.com/microsoft/TypeScript/blob/dbe9e3d237ee82435ef3948b3c479d548ab66b3d/src/tsc/tsc.ts#L133-L134
https://github.com/microsoft/TypeScript/blob/dbe9e3d237ee82435ef3948b3c479d548ab66b3d/src/compiler/watch.ts#L82-L89
but we cannot use this because it is internal function.

So I recommend you to use
https://github.com/microsoft/TypeScript/blob/dbe9e3d237ee82435ef3948b3c479d548ab66b3d/src/compiler/commandLineParser.ts#L1350-L1389

like:
```ts

const configFileName = ts.findConfigFile(__dirname, ts.sys.fileExists);
const optionsToExtend = {};
const result = ts.getParsedCommandLineOfConfigFile(configFileName, optionsToExtend, ts.sys as any);
```
`result`:
```js
{ options:
   { jsx: 2,
     target: 0,
     configFilePath:
      '/path/to/repository/tsconfig.json' },
  fileNames:
   [ '/path/to/repository/src/index.ts' ],
  projectReferences: undefined,
  typeAcquisition: { enable: false, include: [], exclude: [] },
  raw:
   { extends: '@whatasoda/tsconfig/tsconfig.react',
     compilerOptions: { target: 'es3' },
     include: [ 'src/**/*' ],
     exclude: [ 'node_modules' ],
     compileOnSave: undefined },
  errors: [],
  wildcardDirectories: { '/path/to/repository/src': 1 },
  compileOnSave: false,
  configFileSpecs:
   { filesSpecs: undefined,
     includeSpecs: [ 'src/**/*' ],
     excludeSpecs: [ 'node_modules' ],
     validatedIncludeSpecs: [ 'src/**/*' ],
     validatedExcludeSpecs: [ 'node_modules' ],
     wildcardDirectories: { '/path/to/repository/src': 1 } } }
```

Type of the `result` is not matched with yours, but I think you can adjust it

**Comment by whatasoda** [comment]
Thank you. But I still consider it may not works if specified project directory is not same with `node_modules` directory...

Anyway, it works in my environment. I'm looking forward to release.
Thank you, again.

**Comment by plantain-00** [comment]
v2.2.0 should fix this now
