### ISSUE TITLE
Support for type coverage broken down by file

### ISSUE THREAD

**Issue by mattdarveniza** [plantain-00/type-coverage#36]
Hi there, this package is really useful, but I was wondering:  are there any plans to record or expose the coverage broken down by file, rather than just a flat top-level metric?

I had a peek at how the coverage checking is done in `core.js` and it looks like it would be pretty straightforward to retain the per-file coverage metrics and return those on `result` if I'm not misunderstanding. Would you be open to a PR that recorded and returned per-file results if a flag is given?

**Comment by plantain-00** [comment]
It should be available in v2.3.0

**Comment by mattdarveniza** [comment]
Thanks so much!

**Comment by alexcanessa** [comment]
@mattdarveniza I just released https://github.com/alexcanessa/typescript-coverage-report, that uses this package to collect data.

**Comment by plantain-00** [comment]
@alexcanessa Nice tool, I just added a link to the tool: https://github.com/plantain-00/type-coverage/pull/45
