### ISSUE TITLE
typing from monorepo libs should not count

### ISSUE THREAD

**Issue by filosfino** [plantain-00/type-coverage#42]
#### Environment(if relevant):
- ts 3.4.5
- monorepo

#### Code(if relevant):
```
# arkie monorepo
$ yarn build:cache
$ yarn workspace @arkie/coloring-engine coverage --detail
```
#### Expected:
typing from other monorepo libs should not be counted (maybe when `skipLibCheck` is set in tsconfig.json?)

#### Actual:
![image](https://user-images.githubusercontent.com/22309511/76324051-75856080-6320-11ea-9fff-db7bfb660981.png)

**Comment by plantain-00** [comment]
v2.4.1 should fix this.

**Comment by filosfino** [comment]
Would it be better to follow tsconfig.json files/includes setting?

**Comment by plantain-00** [comment]
For example:
```ts
// a.ts
import './b'
```

```ts
// b.ts
```

If `files` or `include` is `["./a.ts"]`, `b.ts` will be compiled by typescript, so if `files` or `include` is followed by type-coverage, then `b.ts`'s `any` will never report.

**Comment by filosfino** [comment]
yep that's right, thanks :)
