### ISSUE TITLE
Cannot use with shared tsconfig with default "main"

### ISSUE THREAD

**Issue by foray1010** [plantain-00/type-coverage#50]
#### Code(if relevant):

```json
{
  "extends": "@foray1010/tsconfig",
  "compilerOptions": {
    "emitDeclarationOnly": false,
    "noEmit": true
  }
}
```

#### Expected:

Able to get config as `tsc`

#### Actual:

```
ENOENT: no such file or directory, stat '/myrepo/node_modules/@foray1010/tsconfig.json'
```

I think the problem is in this line: https://github.com/plantain-00/type-coverage/blob/3e9c564912fc319eff923cd171b6d2caa5c325b6/packages/utils/src/tsconfig.ts#L76

**Comment by plantain-00** [comment]
v2.7.1 should fix this.

**Comment by foray1010** [comment]
it works, thank you!
