### ISSUE TITLE
Shouldn't flag `as const`

### ISSUE THREAD

**Issue by danielnixon** [plantain-00/type-coverage#52]
#### Code(if relevant):

```typescript
"foo" as const
```

#### Expected:

Doesn't count as uncovered

#### Actual:

Is flagged as uncovered

**Comment by plantain-00** [comment]
It's the strict mode

> Type assertion, like a as string, a!, <string>a will be considered as uncovered
Also, future minor release may introduce stricter type check in this mode, which may lower the type coverage rate

https://github.com/plantain-00/type-coverage#strict-mode

You can turn it off by removing `--strict` you don't need it.

**Comment by plantain-00** [comment]
`as const` should not count, I will fix it.

**Comment by plantain-00** [comment]
v2.8.1 should exclude `as const`

**Comment by danielnixon** [comment]
LGTM, thanks @plantain-00.
