### ISSUE TITLE
Unclear why coverage isn't 100%

### ISSUE THREAD

**Issue by danielnixon** [plantain-00/type-coverage#53]
#### Environment(if relevant):

* This project: https://github.com/danielnixon/total-functions
* This commit (2.7.2 -> 2.8.0): https://github.com/danielnixon/total-functions/commit/3006021fe3c1f47c8551e1da945d6418d15b5342
* Corresponding build output: https://travis-ci.org/github/danielnixon/total-functions/builds/700502123#L216

#### Code(if relevant):

```bash
yarn type-coverage --strict --ignore-catch --detail
yarn run v1.22.4
$ type-coverage --strict --detail --ignore-catch
328 / 332 98.79%
The type coverage rate(98.79%) is lower than the target(100%).
error Command failed with exit code 1.
```

#### Expected:

Either coverage is 100% OR the failing code is identified in the output (especially with `--detail` flag).

#### Actual:

The coverage is reported as 98.79% but no failing code is identified, even with `--detail` flag.

**Comment by danielnixon** [comment]
Is it that the lines ignored with `// type-coverage:ignore-line` are still contributing to the overall percentage?

**Comment by plantain-00** [comment]
`--strict` should be work with `// type-coverage:ignore-line`, I will fix it.

**Comment by plantain-00** [comment]
v2.8.1 should fix it.

**Comment by danielnixon** [comment]
LGTM, thanks @plantain-00 !
