### ISSUE TITLE
Shouldn't flag `as unknown`

### ISSUE THREAD

**Issue by danielnixon** [plantain-00/type-coverage#54]
#### Code(if relevant):

```typescript
const foo = someAnyValue as unknown;
```

#### Expected:

`as unknown` should be allowed (even in strict mode). Consider an `any` (or some other bad type) from a third party library that you want to treat (safely) as unknown.

#### Actual:

`as unknown` is flagged as untyped (when in strict mode).

**Comment by plantain-00** [comment]
fixed in v2.8.2

**Comment by danielnixon** [comment]
LGTM, thanks @plantain-00
