### ISSUE TITLE
Shouldn't flag safe `as` type assertions

### ISSUE THREAD

**Issue by danielnixon** [plantain-00/type-coverage#55]
#### Code(if relevant):

Same situation as #52 and #54, but this one might be more controversial.

There are some "safe" `as` type assertions that probably shouldn't be flagged as untyped.

```typescript
const foo = 1 as number; // useless but not unsafe
```

```typescript
const foo = 1 as number & PositiveNumber; // intersection (tagged) type
const bar = foo as number; // throwing away the type tag. `number` is supertype of `number & PositiveNumber` so this is safe too
```

```typescript
const foo = 1 as const;
const bar = foo as number; // widening type by throwing away the knowledge of number literal
```

#### Expected:

These safe examples are not flagged as untyped.

#### Actual:

These safe examples are flagged as untyped.

**Comment by danielnixon** [comment]
I recommend relaxing this rule as much as humanly possible for the "safe" cases, because what amount to false positives will discourage use of strict mode, which we want to encourage!

**Comment by plantain-00** [comment]
Widen type seems not safe:

```ts
const foo = "aaa" as unknown
const bar = foo as number // <- here
```

**Comment by danielnixon** [comment]
Yep that's basically a downcast and definitely not safe. Flagging that as untyped is legit. 👍 

FWIW here are the test cases for an ESLint I'm writing with very similar goals: https://github.com/danielnixon/eslint-plugin-total-functions/blob/master/src/rules/no-unsafe-type-assertion.test.ts

**Comment by danielnixon** [comment]
Somewhat related: https://github.com/microsoft/TypeScript/issues/7481

**Comment by plantain-00** [comment]
I think no enough gain for the complexity.
And I think compared to `const foo = "aaa" as unknown as number`, `const foo: number = "aaa" as unknown` is safer, typescript can find the error.
Your proposed cases can be rewritten by that or `as const`, for example:

```ts
const foo = 42 as number
const foo = 42 as const

const foo = 'foo' as 'foo' | 'bar'
const foo: 'foo' | 'bar' = 'foo'

type Foo = { readonly foo: string | undefined }
const foo = {} as Foo
const foo: Foo = {}
```

**Comment by danielnixon** [comment]
> I think no enough gain for the complexity.

This is a fair point.

> And I think compared to const foo = "aaa" as unknown as number, const foo: number = "aaa" as unknown is safer, typescript can find the error.

This is a fair point too, but in my thinking `string as unknown` would be considered safe (so would not be flagged as untyped) but `unknown as number` would definitely be considered unsafe (so would be flagged as untyped).

**Comment by plantain-00** [comment]
> but in my thinking string as unknown would be considered safe (so would not be flagged as untyped) but unknown as number would definitely be considered unsafe (so would be flagged as untyped).

That's what's going on.

**Comment by danielnixon** [comment]
This looks like it's covered by https://github.com/plantain-00/type-coverage/commit/b76b2a36c5abc13959a3a04ef69811a526d3362a (nice work) so closing this issue now.

**Comment by danielnixon** [comment]
Although... https://github.com/microsoft/TypeScript/pull/33263/files#r335215697

**Comment by plantain-00** [comment]
I checked whether `isTypeAssignableTo` exists, I think it's OK if I releasing a quick fix if `isTypeAssignableTo` breaks.

**Comment by danielnixon** [comment]
A few (maybe) interesting cases that are considered unsafe according to `isTypeAssignableTo`'s assignability rules but are arguably safe:

```ts
type Foo = { readonly foo: string };
const foo = {foo: 'foo', bar: 'bar'} as Foo;
```

```ts
type Foo = { readonly foo: undefined };
const foo = {} as Foo;
```

```ts
type Foo = { readonly foo: string | undefined };
const foo = {} as Foo;
```

I don't think I feel strongly about whether these should be considered typed or untyped (safe or unsafe) but sharing just in case there's a way (and a desire) to relax the rules even further.

The counterargument that `isTypeAssignableTo` is gospel truth is hard to argue with.
