### ISSUE TITLE
CHANGELOG is missing

### ISSUE THREAD

**Issue by JounQin** [plantain-00/type-coverage#57]
As title.

**Comment by plantain-00** [comment]
CHANGELOG for only breaking changes is in README.md: https://github.com/plantain-00/type-coverage#changelogs

**Comment by JounQin** [comment]
I've noticed that but it would be nice to have CHANGELOG for every patch release too.

**Comment by plantain-00** [comment]
I think CHANGELOG for every minor and patch release is basically same with the commit messages.
If it's needed, I will write a script to generate it from commit messages.

**Comment by JounQin** [comment]
> CHANGELOG for every minor and patch release is basically same with the commit messages.

That's my point. CHANGELOG is easier to read then commit messages.

**Comment by JounQin** [comment]
close in favor of https://github.com/plantain-00/type-coverage/blob/master/CHANGELOG.md
