### ISSUE TITLE
Support `unknown` on catch clauses

### ISSUE THREAD

**Issue by danielnixon** [plantain-00/type-coverage#59]
In TypeScript 4.0 we can finally treat caught exceptions as `unknown` instead of `any`.

From https://devblogs.microsoft.com/typescript/announcing-typescript-4-0-beta/#unknown-on-catch:

```ts
try {
    // ...
}
catch (e: unknown) {
    // error!
    // Property 'toUpperCase' does not exist on type 'unknown'.
    console.log(e.toUpperCase());

    if (typeof e === "string") {
        // works!
        // We've narrowed 'e' down to the type 'string'.
        console.log(e.toUpperCase());
    }
}
```

It would be good to consider these typed/safe (even when `--ignore-catch` is false).

See also
* https://github.com/typescript-eslint/typescript-eslint/pull/2306
* https://github.com/typescript-eslint/typescript-eslint/issues/2260

**Comment by plantain-00** [comment]
`v2.10.0-beta.0` support typescript 4 beta now.
