### ISSUE TITLE
Deal with type guards in strict mode

### ISSUE THREAD

**Issue by darky** [plantain-00/type-coverage#61]
#### Version(if relevant): 2.10.0

https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards

In TypeScript documentation for using user defined type guards need to use `as` for correct property check.
How to implement user defined type guards with **type-coverage** with strict mode?
Use of `as` is forbidden.

**Comment by plantain-00** [comment]
I think it's not safe, for example:

```ts
type Fish = { foo: { bar: number } };
type Bird = { baz: number };

function isFish(pet: Fish | Bird): pet is Fish {
  return (pet as Fish).foo.bar !== undefined;
}

isFish({ baz: 1 })
```

The error is: Cannot read property 'bar' of undefined

**Comment by darky** [comment]
`return (pet as Fish).foo?.bar !== undefined;` is safe.

**Comment by plantain-00** [comment]
I mean `pet as Fish` is not safe.
`safe` does not means `always valid`, for example:

```ts
function foo(bar: any) { // I found `bar` is any(not safe), so I report it
  return bar.baz // `foo` may or may not has `baz`, so it is not safe
}
```
