### ISSUE TITLE
Split strict flag to particular

### ISSUE THREAD

**Issue by darky** [plantain-00/type-coverage#62]
Now for all cases exists only one `strict` flag. But very hard to satisfy all strictness at once. 
Would be good to split `strict` flag to multiple like `strict-as`, `strict-nested`, `strict-optional`
`strict` flag preserve old behaviour, that all flags plug on.

**Comment by plantain-00** [comment]
This tool is not like `tsc` or `eslint`, they just fail if one case fails, but this tool is progressive, you don't have to be `--at-least 100`.
if some cases fail, maybe `--at-least 99.99` can still make CI happy, you can still improve your code and the coverage number to 100 if you have time later.
I think splitting strict flag is too complex, they are doing same things, checking unsafe code.

**Comment by plantain-00** [comment]
`v2.16.0` should support it.
