### ISSUE TITLE
tsserver plugin

### ISSUE THREAD

**Issue by darky** [plantain-00/type-coverage#64]
Would good to have type-coverage plugin for tsserver, which can show uncovered code in your IDE.
I see it https://github.com/plantain-00/type-coverage/issues/5
But it only VSCode story.

Some projects for inspiration:
https://github.com/xialvjun/ts-sql-plugin
https://github.com/Quramy/ts-graphql-plugin

**Comment by plantain-00** [comment]
v2.12 supports it now.
And docs: https://github.com/plantain-00/type-coverage#the-typescript-language-service-plugin-of-type-coverageadded-in-v212

**Comment by darky** [comment]
Great feat! Thanks! :1st_place_medal:  :100:  :tada:
