### ISSUE TITLE
Cache option is missing in `LintOptions`

### ISSUE THREAD

**Issue by alexcanessa** [plantain-00/type-coverage#70]
#### Version: 2.14.2

The `LintOptions` interface should have been updated when `--cache` option was added as part of #16.

Should be pretty straight forward fix.

**Comment by alexcanessa** [comment]
Unless is the same as `enableCache`?

**Comment by plantain-00** [comment]
`enableCache` is same as `--cache`

**Comment by alexcanessa** [comment]
Ok thanks 👍 

Just added all latest options to typescript-coverage-report (https://github.com/alexcanessa/typescript-coverage-report/pull/31).

That required a bit of mapping 😅
