### ISSUE TITLE
Message "warning: unhandled node kind: 191"

### ISSUE THREAD

**Issue by aywan** [plantain-00/type-coverage#71]
#### Environment: 
docker, alpine 
node:12.16.2 custom container 
node:12.19.1-alpine3.10 - stock, docker hub container

#### Code:
```
const useFormProcessing = (): [isProcessing: boolean, changeState: (name:  string, state?: boolean) => void] => {
....
}
```

Running with debug mode allow to find place where message appears. 
Problem with [Labeled Tuple Elements](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#labeled-tuple-elements).
If remove labels - all ok.
Can you help me to find a problem?

Looks like same issue at type-coverage-report: https://github.com/alexcanessa/typescript-coverage-report/issues/25

**Comment by plantain-00** [comment]
v2.14.3 should fix this.

**Comment by aywan** [comment]
I confirm v2.14.3  fixes the bug
