### ISSUE TITLE
Message: "warning: unhandled node kind: 193"

### ISSUE THREAD

**Issue by xf3** [plantain-00/type-coverage#73]
#### Code:

```
type World = 'world';

export type Greeting = `hello ${World}`;
```
Similar to https://github.com/plantain-00/type-coverage/issues/71, the problem is caused by newly added Typescript's template literal types: https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#template-literal-types

**Comment by plantain-00** [comment]
v2.14.6 should fix this.

**Comment by xf3** [comment]
Fixed, great job, thank you!
