### ISSUE TITLE
SyntaxKind.NamespaceExport not supported

### ISSUE THREAD

**Issue by xf3** [plantain-00/type-coverage#77]
#### Code:

```
export * as Components from './components';
```

#### Expected:
Code parsed normally

#### Actual:
Getting error _warning: unhandled node kind: 269_

**Comment by plantain-00** [comment]
v2.14.9 should fix this.

**Comment by xf3** [comment]
Fixed, thank you!

**Comment by JounQin** [comment]
Confirmed fixed issue should be closed.
