### ISSUE TITLE
`glob_1.default is not a function` with 2.15.0

### ISSUE THREAD

**Issue by martinfrancois** [plantain-00/type-coverage#79]
We are using `type-coverage` as part of our CI pipeline. So far everything has been working well, but since the 2.15.0 release, we get the following error on our code base (did not appear before with 2.14.9): `glob_1.default is not a function`

We use the following command to run `type-coverage` in ci:
```
npx --package typescript --package type-coverage -c 'type-coverage -p tsconfig.json --strict --ignore-files "src/api/generated/**/*.*"'
```

#### tsconfig.json
```json
{
  "compilerOptions": {
    "baseUrl": "./src",
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "noImplicitAny": false,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "paths": {
    "widgets/*": ["widgets/*"]
  },
  "include": ["src"]
}
```

#### Environment(if relevant): reproducible under different environments, Node 15.8.0, npm 7.5.1 (for example, Dockerhub image `node:15`)

**Comment by plantain-00** [comment]
v2.15.1 should fix this.

**Comment by martinfrancois** [comment]
It does indeed, thanks a lot for the swift response!
