### ISSUE TITLE
Doesn't recognize BigInt from TypeScript 3.2

### ISSUE THREAD

**Issue by karol-majewski** [plantain-00/type-coverage#8]
#### Environment(if relevant):

TypeScript 3.2.2

#### Code(if relevant):

```ts
type Primitive =
  | boolean
  | number
  | bigint
  | string
  | symbol
  | null
  | undefined;
```

#### Expected:

No error nor warning.

#### Actual:

A warning about `bigint` is emitted.

> node: typings/global.d.ts:12:7: bigint 146(kind)
> warning: unhandled node kind: 146

**Comment by plantain-00** [comment]
Thanks for report this, v1.6.2 should fix this

**Comment by karol-majewski** [comment]
It did, thank you. 🙇
