### ISSUE TITLE
[feature request] a new option to ignore `Non-null assertion operator`

### ISSUE THREAD

**Issue by JounQin** [plantain-00/type-coverage#80]
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator

Sometimes, we can just confirm the value is non null.

```ts
transform('async function main() {}', {
  filename: 'fast-async.test.js',
  presets: ['@1stg'],
})!.code
```

#### Expected:

Pass

#### Actual:

Fail

**Comment by plantain-00** [comment]
It's duplicated as #62 
Since it's more needed than I expected, I will add it in the next few days.

**Comment by plantain-00** [comment]
`v2.16.0` should support it.

**Comment by JounQin** [comment]
I tried but it seems not working. 😂

```log
/Users/JounQin/Workspaces/GitHub/configs/tests/test.spec.ts:6:7: transform('async function main() {}', {
        filename: 'fast-async.test.js',
        presets: ['@1stg'],
      })!
109 / 110 99.09%
The type coverage rate(99.09%) is lower than the target(100%).
```

**Comment by plantain-00** [comment]
Did you use `--ignore-non-null-assertion`?

**Comment by JounQin** [comment]
It should be ralted to cache. I used `type-coverage --ignore-xxx` before, and changed to use config settings in `package.json` after upgrading.

```json
{
  "typeCoverage": {
    "atLeast": 100,
    "cache": true,
    "detail": true,
    "ignoreCatch": true,
    "ignoreFiles": "*.d.ts",
    "ignoreNonNullAssertion": true,
    "strict": true
  }
}
```

I tried to run `type-coverage --ignore-non-null-assertion` again, it works, and then run `type-coverage` no error too, but I doubt the cache is correct, so U decide to delete `.type-coverage` folder, now it should work as expected.

**Comment by JounQin** [comment]
@plantain-00 Are you going to check the problem of cache, or should I close this issue?

**Comment by plantain-00** [comment]
I will check it in next few days, I don't have time now.

**Comment by plantain-00** [comment]
In `v2.16.1`, it should work with `--cache`
