### ISSUE TITLE
Parameter incorrectly flagged as any when type applied to whole function

### ISSUE THREAD

**Issue by danvk** [plantain-00/type-coverage#82]
#### Code(if relevant):

```ts
export const checkedFetch: typeof fetch = async (input, init) => {
  const r = await fetch(input, init);
  if (r.status !== 200) {
    throw new Error(`${r.status} ${r.statusText}`);
  }
  return r;
};
```

#### Expected:

The `input` and `init` params have types.

#### Actual:

`type-coverage` reports that they have `any` types.

You can see from [this playground][1] that the `typeof fetch` is sufficient to get contextual types for the function params:

![image](https://user-images.githubusercontent.com/98301/108756662-cf257180-7516-11eb-97eb-330cc9163e14.png)

[1]: https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAYwgOwM7wQC2Ag1sAEwDFgYsAuOGATzGAgDM4HSs4BeOAQ1WuQTgAKAJbIwAVxgAaOKOEwAlBwB8cAN4AoOIhTo4UDtwDuXec1aYRYyTLmKA3FtlNBUAHTouMcajgBCdk4AJgAGEKVNbW0YTCgIIzhkYASAUSg4qEEAAwASNXdPb1QAXzg8gpgvHwAVUBhirIVHbWKnKFJxKGR9R2LHIA

**Comment by plantain-00** [comment]
I can't reproduce it with `--strict`

```txt
17 / 17 100.00%
```

Maybe your `tsconfig.json` `lib` didn't include `dom`

**Comment by danvk** [comment]
This seems to be related to the issue from #83; I can reproduce this only if I add an `exclude: []` section to my `tsconfig.json`.

**Comment by plantain-00** [comment]
v2.16.2 should fix this

**Comment by danvk** [comment]
fix confirmed, thanks @plantain-00!
