### ISSUE TITLE
Inaccurate any after non-null assertion

### ISSUE THREAD

**Issue by danvk** [plantain-00/type-coverage#83]
#### Code(if relevant):

```ts
document.querySelector('#toggle')!.addEventListener('click', e => {
  e.preventDefault();
}
```

#### Expected:

no anys

#### Actual:

`e` and `preventDefault` are flagged as having `any` types.

Maybe this is the same as #80, I couldn't quite tell.

I ran

    type-coverage --ignore-catch --ignore-unread

**Comment by plantain-00** [comment]
It should be `--ignore-non-null-assertion` rather than `--ignore-unread`

**Comment by danvk** [comment]
I put together a full repro here: https://gist.github.com/danvk/483d281abe0604e953872caba40ea505

I can only reproduce this issue if I add an `exclude` section to my `tsconfig.json`. Removing that section (even if it's an empty list) makes this work correctly. I tried passing `--ignore-non-null-assertion` but it had no effect.

**Comment by plantain-00** [comment]
v2.16.2 should fix this

**Comment by danvk** [comment]
fix confirmed, thanks!
