### ISSUE TITLE
Trim prefix path for CI (CLI only)

### ISSUE THREAD

**Issue by septs** [plantain-00/type-coverage#88]
#### Code(if relevant):

```
// code here
```

#### Expected:

via an flag control trim common prefix path.

in CI working environment prefix path all the same.

#### Actual:

trim prefix path on CI

**Comment by plantain-00** [comment]
You mean `home/runner/work/type-coverage/type-coverage/packages/core/src/tsconfig.ts` to be `packages/core/src/tsconfig.ts`?

**Comment by septs** [comment]
yep

**Comment by septs** [comment]
i think, same prefix path meaningless.

**Comment by plantain-00** [comment]
v2.17.0 supports `--show-relative-path`
