### ISSUE TITLE
0 / 0 NaN% type-coverage success.

### ISSUE THREAD

**Issue by Jack-Works** [plantain-00/type-coverage#91]
#### Environment(if relevant): Windows

It seems like the new glob lib does not support windows well. It displays this on Windows machine while works well on CI.

```js
0 / 0 NaN%
type-coverage success.
```

**Comment by cdrini** [comment]
Also getting the same error on Windows, although I went back to 2.10.x and still saw the issue. As a workaround for any Windows users, running it inside docker worked:

```sh
docker run -it --rm -v /$(pwd)://app -w //app node:14 npx type-coverage
```

In case it's useful:

```sh
$ tsc --version
3.8.3
```

**Comment by cdrini** [comment]
I also tried updated typescript to latest `4.2.4`, but no luck.

**Comment by Jack-Works** [comment]
> although I went back to 2.10.x and still saw the issue. 

@cdrini you need to make sure the transitive dependency `type-coverage-core` also gets downgraded. please check out your lockfile to verify if it is really 2.10.x

**Comment by plantain-00** [comment]
Can you provide `tsconfig.json` `include` and `exclude`? @Jack-Works  @cdrini

**Comment by Jack-Works** [comment]
Our project is https://github.com/DimensionDev/Maskbook

The main tsconfig is [/tsconfig.json](https://github.com/DimensionDev/Maskbook/blob/master/tsconfig.json), type-coverage is running on [/packages/maskbook/](https://github.com/DimensionDev/Maskbook/tree/master/packages/maskbook) which using [this tsconfig](https://github.com/DimensionDev/Maskbook/blob/master/packages/maskbook/tsconfig.json) and have content:

```jsonc
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "rootDirs": ["./src/", "./abis/"],
    "outDir": "./dist/"
  },
  "include": ["./src/**/*.tsx", "./src/**/*.ts", "./src/**/*.json", "./abis/*.json"],
  "references": [{ "path": "../shared/" }, { "path": "../theme/" }, { "path": "../icons/" }]
}
```

**Comment by plantain-00** [comment]
v2.17.3 should fix this

**Comment by cdrini** [comment]
Confirmed working for me on 2.17.3 :+1: Thank you @plantain-00 !

**Comment by Jack-Works** [comment]
works for me too thanks!
