### ISSUE TITLE
Unexpected report on `String#replace`

### ISSUE THREAD

**Issue by JounQin** [plantain-00/type-coverage#96]
#### Code(if relevant):

```ts
const camelCase = (val: string) =>
  val.replace(/-([\da-z])/g, ([_, $0]) => $0.toUpperCase())
```

#### Expected:

No report

#### Actual:

```log
scripts/build.ts:45:32: _
scripts/build.ts:45:35: $0
scripts/build.ts:45:43: $0
scripts/build.ts:45:46: toUpperCase
154 / 158 97.46%
```

See [ts playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAYwgOwM7wQQwLbADYDCmqwcAvHABQBumeAXHOlAJbIDmAlOQHwBQcOLTwA6KMDB5MCYJQD0AWkoBtADoATTAoBeAXU5z2AGirKA+iYAkABn284NkTAgBVMGGBQiJSp05A)

**Comment by plantain-00** [comment]
your `string. replace`'s type definition is at `lib.es2015.symbol.wellknown.d.ts`, you can check whether your `-p tsconfig.json` contains `ES2015`.

**Comment by JounQin** [comment]
@plantain-00 

My tsconfig:

```json
{
  "extends": "@1stg/tsconfig/lib"
}
```

It is using `"lib": ["ESNext"]` inside.

**Comment by plantain-00** [comment]
What I tried:

```json
{
  "extends": "@1stg/tsconfig/lib" // no error from type-coverage and vscode
}
```

```json
{
  "extends": "@1stg/tsconfig/lib",
  "compilerOptions": {
    "target": "es5" // errored from type-coverage and vscode
  }
}
```

```json
{
  "extends": "@1stg/tsconfig/lib",
  "compilerOptions": {
    "target": "es5",
    "downlevelIteration": true // no error from type-coverage and vscode
  }
}
```

**Comment by JounQin** [comment]
@plantain-00 Wired, can you please try https://github.com/JounQin/remark-preset-prettier/tree/fix/esm for reproduction?

**Comment by plantain-00** [comment]
I remove the `// type-coverage:ignore-next-line -- https://github.com/plantain-00/type-coverage/issues/96` and get

```
$ yarn typecov
yarn run v1.22.4
$ type-coverage
158 / 158 100.00%
type-coverage success.
✨  Done in 4.76s.
```

**Comment by plantain-00** [comment]
Maybe your error comes from the cached result, try to delete `.type-coverage` and do it again.

**Comment by JounQin** [comment]
![image](https://user-images.githubusercontent.com/8336744/129441070-564c4284-9369-406e-aa54-1f54101a9bf4.png)

I've tried to delete `.type-coverage` a lot of times.🤣

**Comment by JounQin** [comment]
OK, I found that it results 100% on Node 14 while lower on Node 12.

**Comment by JounQin** [comment]
That is very weird, that after reinstall node 12 via `nvm install 12`, there is no issue...

Close for now.

**Comment by JounQin** [comment]
...

See https://github.com/JounQin/remark-preset-prettier/runs/3328501669#step:8:29

**Comment by JounQin** [comment]
should be related to #101

**Comment by JounQin** [comment]
Sorry, it still error https://github.com/JounQin/remark-preset-prettier/runs/5740767638?check_suite_focus=true

**Comment by JounQin** [comment]
Maybe related to `extends node_modules json with same name dir` like [privatenumber/get-tsconfig@`532bee9` (#21)](https://github.com/privatenumber/get-tsconfig/pull/21/commits/532bee99dc78c6b88ac5ef7b71988e95d9957c18)
